-- MySQL Script generated by MySQL Workbench
-- 05/20/17 12:22:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inventory` ;

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventory` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema inventory_warehouse
-- -----------------------------------------------------
USE `inventory` ;

-- -----------------------------------------------------
-- Table `inventory`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`items` (
  `itemId` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lot` INT NULL,
  `color` INT NULL,
  `size` INT NULL,
  `price` FLOAT(10,2) NOT NULL DEFAULT 0,
  `isActived` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`itemId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`users_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`users_type` (
  `idusers_type` INT NOT NULL AUTO_INCREMENT,
  `name_type` VARCHAR(45) NULL,
  `code_type` VARCHAR(2) NULL,
  PRIMARY KEY (`idusers_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`users` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password_user` VARCHAR(45) NULL,
  `idusers_type` INT NOT NULL,
  `isActived` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_users_users_type`
    FOREIGN KEY (`idusers_type`)
    REFERENCES `inventory`.`users_type` (`idusers_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_users_users_type_idx` ON `inventory`.`users` (`idusers_type` ASC);


-- -----------------------------------------------------
-- Table `inventory`.`warehouses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`warehouses` (
  `warehouses_Id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `isActived` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`warehouses_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`type_doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`type_doc` (
  `type_doc_Id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(4) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`type_doc_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`document` (
  `document_id` INT AUTO_INCREMENT,
  `type_doc_Id` INT NOT NULL,
  `consecutive` INT not null,
  `document_date` DATETIME NOT NULL,
  PRIMARY KEY (`document_id`),
  CONSTRAINT `fk_document_type_doc1`
    FOREIGN KEY (`type_doc_Id`)
    REFERENCES `inventory`.`type_doc` (`type_doc_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_document_type_doc1_idx` ON `inventory`.`document` (`type_doc_Id` ASC);


-- -----------------------------------------------------
-- Table `inventory`.`document_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory`.`document_detail` (
  `document_datail_Id` INT NOT NULL AUTO_INCREMENT,
  `document_id` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `price` FLOAT(12,2) NOT NULL,
  `warehouses_Id` INT NOT NULL,
  `itemId` INT NOT NULL,
  PRIMARY KEY (`document_datail_Id`),
  CONSTRAINT `fk_document_datail_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `inventory`.`document` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_detail_warehouses1`
    FOREIGN KEY (`warehouses_Id`)
    REFERENCES `inventory`.`warehouses` (`warehouses_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_detail_items1`
    FOREIGN KEY (`itemId`)
    REFERENCES `inventory`.`items` (`itemId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_document_datail_document1_idx` ON `inventory`.`document_detail` (`document_id` ASC);

CREATE INDEX `fk_document_detail_warehouses1_idx` ON `inventory`.`document_detail` (`warehouses_Id` ASC);

CREATE INDEX `fk_document_detail_items1_idx` ON `inventory`.`document_detail` (`itemId` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `inventory`.`users_type` (`name_type`, `code_type`) VALUES ('Consultas', 'C');
INSERT INTO `inventory`.`users_type` (`name_type`, `code_type`) VALUES ('Jefe de Bodega', 'J');


INSERT INTO `inventory`.`users` (`name`, `password_user`, `idusers_type`, `isActived`) VALUES ('Javier', '123456', 1,1);
INSERT INTO `inventory`.`users` (`name`, `password_user`, `idusers_type`, `isActived`) VALUES ('Ramiro', '123456', 2,1);
INSERT INTO `inventory`.`users` (`name`, `password_user`, `idusers_type`, `isActived`) VALUES ('David', '123456', 1,1);
INSERT INTO `inventory`.`users` (`name`, `password_user`, `idusers_type`, `isActived`) VALUES ('Dz', '123456', 2,1);


INSERT INTO `inventory`.`items` (`code`, `name`, `lot`, `color`, `size`, `price`, `isActived`)
	VALUES ('1', 'Portatil', '0', '0', '0', '1500000', '1'),
    ('2', 'Tablet', '0', '0', '0', '400000', '1'),
    ('3', 'Computador i5' , 0 , 0, 0, 2000000, 1),
    ('4', 'Computador i7' , 0 , 0, 0, 2500000, 1),
    ('5', 'Monitor 23"' , 0 , 0, 0, 800000, 1),
    ('6', 'Disco Duro SSD 500gb' , 0 , 0, 0, 600000, 1);

INSERT INTO `inventory`.`type_doc` (`code`, `name`) VALUES ('1', 'Ingreso');
INSERT INTO `inventory`.`type_doc` (`code`, `name`) VALUES ('2', 'Salida');

INSERT INTO `inventory`.`warehouses` (`code`, `name`, `isActived`) VALUES ('1', 'Principal', '1');insert into inventory.document values ( 1, 1, '000000001', current_date());
insert into inventory.document values ( 2, 1, '000000002', current_date());
insert into inventory.document values ( 3, 2, '000000003', current_date());
insert into inventory.document values ( 4, 2, '000000004', current_date());

INSERT INTO `inventory`.`document_detail`(`document_datail_Id`,`document_id`,`Quantity`,`price`,`warehouses_Id`,`itemId`)
-- VALUES(<{document_datail_Id: }>,<{document_id: }>,<{Quantity: }>,<{warehouses_Id: }>,<{itemId: }>);
VALUES (1, 1, 2,150000, 1, 1) , (2,2, 1 ,150000,1, 2), (3, 3, 5 ,150000, 1, 3) , (4, 4, 3,150000, 1, 4);


-- Verificación
SELECT d.consecutive,
			td.name tipo_movimiento,
            d.document_date fecha,
            Concat( it.code ,' ', it.name)  articulo,
            dd.Quantity cantidad,
            wa.name bodega 
            FROM inventory.document d 
inner join inventory.type_doc td on d.type_doc_Id = td.type_doc_Id
inner join inventory.document_detail dd on d.document_id = dd.document_id
inner join inventory.warehouses wa on dd.warehouses_id = wa.warehouses_id
inner join inventory.items it on it.itemId = dd.itemId




